[package]
name = "consolegl"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0"
description = "A terminal 3D graphics library"

[dependencies]
cgmath = "0.18.0"
crossterm = "0.28.1"
nalgebra = "0.33.2"
parry3d = "0.17.4"
